name: strcar
description: Strcar OBD/ELM universal diagnostic app
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Planned feature dependencies (not all used yet)
  flutter_reactive_ble: ^5.2.0
  flutter_bluetooth_serial: ^0.4.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3
  logger: ^2.3.0
  flutter_tts: ^3.8.0
  pdf: ^3.11.0
  printing: ^5.13.0
  intl: ^0.20.2
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

